builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

changelog:
  use: github
  filters:
    exclude:
      - '^docs'
      - '^test'
      - "^ci"
      - "^typo"
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug fixes'
      regexp: '^.*?bug(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999

aurs:
  - homepage: "https://github.con/nikaro/goresume"
    description: "Build HTML/PDF resume from JSON/YAML/TOML."
    maintainers:
      - "Nicolas Karolak <nicolas at karolak dot fr>"
    license: "MIT"
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/goresume-bin.git"

brews:
  - homepage: "https://github.con/nikaro/goresume"
    description: "Build HTML/PDF resume from JSON/YAML/TOML."
    license: "MIT"
    tap:
      owner: "nikaro"
      name: "homebrew-tap"
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    folder: "Formula"
    install: |-
      bin.install "goresume"
      generate_completions_from_executable(bin/"goresume", "completion")

nfpms:
  - homepage: "https://github.con/nikaro/goresume"
    description: "Build HTML/PDF resume from JSON/YAML/TOML."
    maintainer: "Nicolas Karolak <nicolas@karolak.fr>"
    license: "MIT"
    formats:
      - "apk"
      - "deb"
      - "rpm"
