# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
---
version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

aurs:
  - homepage: "https://github.con/nikaro/goresume"
    description: "Build HTML/PDF resume from JSON/YAML/TOML."
    maintainers:
      - "Nicolas Karolak <nicolas at karolak dot fr>"
    license: "MIT"
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/goresume-bin.git"

nfpms:
  - homepage: "https://github.con/nikaro/goresume"
    description: "Build HTML/PDF resume from JSON/YAML/TOML."
    maintainer: "Nicolas Karolak <nicolas@karolak.fr>"
    license: "MIT"
    formats:
      - "apk"
      - "deb"
      - "rpm"
