name: CD

on:
  push:
    tags: [v*]

permissions:
  contents: write
  id-token: write
  pages: write

env:
  # renovate: datasource=github-releases depName=jgm/pandoc
  PANDOC_VERSION: 3.1

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      AUR_KEY: ${{ secrets.AUR_KEY }}
      GITHUB_TOKEN: ${{ github.token }}
      HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - uses: actions/setup-go@v4
        with:
          cache: true
          check-latest: true
          go-version-file: go.mod
      - run: git fetch --force --tags
      - uses: goreleaser/goreleaser-action@v5
        with:
          args: release --clean

  page:
    name: Page
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - uses: actions/configure-pages@v3
      - uses: actions/setup-go@v4
        with:
          cache: true
          check-latest: true
          go-version-file: go.mod
      - run: ansible -b -m apt -a deb=https://github.com/jgm/pandoc/releases/download/${{ env.PANDOC_VERSION }}/pandoc-${{ env.PANDOC_VERSION }}-1-amd64.deb localhost
      - run: make docs
      - uses: actions/upload-pages-artifact@v2
        with:
          path: docs/
      - uses: actions/deploy-pages@v2
        id: deploy
