name: CD

on:
  push:
    tags: [v*]

permissions:
  contents: write

jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      AUR_KEY: ${{ secrets.AUR_KEY }}
      GITHUB_TOKEN: ${{ github.token }}
      HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          cache: true
          check-latest: true
          go-version-file: go.mod
      - uses: goreleaser/goreleaser-action@v4
        with:
          args: release --clean
