name: Releases

on:
  push:
    tags: [v*]

jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AUR_KEY: ${{ secrets.AUR_KEY }}
      GH_PAT: ${{ secrets.GH_PAT }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          cache: true
          check-latest: true
          go-version-file: go.mod
      - uses: goreleaser/goreleaser-action@v4
